### ISSUE TITLE
stack rolled back

### ISSUE THREAD

**Issue by chenglian** [aws-samples/aws-textract-comprehend-lex-chatbot#3]
Stack creation rolled back due to ERROR "CodeBuildDeploy | CREATE_FAILED | Parameters: [Timestamp] must have values"

**Comment by srikrishnaseshadri** [comment]
Same status as #chenglian

**Comment by chethancmk** [comment]
The issue is now resolved, the template cfntemplate.yml has been updated to add the mandatory timestamp parameter and synched with the s3 bucket . The launch template is working fine now.

**Comment by premranga** [comment]
confirmed, working as expected
